name: npm-publish

on:
  push:
    branches:
      - main
    tags:
      - "!*"
jobs:
  release:
    name: check version, add tag and release
    runs-on: ubuntu-latest
    timeout-minutes: 30 # job全体
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          registry-url: https://npm.pkg.github.com/
          always-auth: true
      - uses: actions/cache@v2
        with:
          path: ~/.cache/yarn/
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-node12
      - name: Can Publish
        run: npx can-npm-publish --verbose
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Install
        run: yarn --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Publish
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
